language: android

env:
- BUILD_TOOLS_VERSION=28.0.3

android:
  components:
  # Use the latest revision of Android SDK Tools
  - tools
  - platform-tools

  # When changing the following, change also in build.gradle!
  - build-tools-${BUILD_TOOLS_VERSION}
  - android-23

  - extra-android-m2repository

  - sys-img-armeabi-v7a-android-23

before_install:
# Avoid ./gradlew: Permission denied
- chmod +x gradlew

install:
# Avoids "Failed to install the following Android SDK packages as some licences have not been accepted."
- echo yes | sdkmanager "build-tools;${BUILD_TOOLS_VERSION}"

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
# Use assembleRelease here to make sure the changes have not affected proguard
- ./gradlew clean build connectedCheck assembleRelease --stacktrace
